DEVICE: cpu
CHECKPOINT_PATH: /workspace/checkpoints/mod_eff_net.pth
CLASS_NAME:
  - Чашка межосевого дифференциала передняя
  - Крестовина межосевого дифференциала
  - Шестерня привода среднего моста
  - Чашка межосевого дифференциала задняя
  - Муфта шестерни привода МОДа
  - Кольцо упорное 130 шестерни МОД
  - Подсборка 0
  - Подсборка 1
  - Подсборка 1а
  - Подсборка 2
  - Подсборка 3
  - Подсборка 4
  - Подсборка 4а
  - Подсборка 4 пол.1
  - Подсборка 5.1
  - Подсборка 5.2
  - Подсборка 5.3
  - Подсборка 5
  - Подсборка 6
  - Подсборка 8
  - Подсборка 9
  - Подсборка 9а
  - Подсборка 5.1 ошибка
  - Подсборка 5.2 ошибка
  - Подсборка 5.3 ошибка
  - Подсборка 5 ошибка
  - Подсборка 5а ошибка
  - Подсборка 10z ошибка
  - Подсборка 6 ошибка
  - Подсборка 6а ошибка
NUM_CLASSES: 30
