version: "3.8"
services:
  rmq:
    image: "rabbitmq:3.8.14-management"
  tgbot:
    image: tgbot
    profiles: ["bot"]
    depends_on:
      - rmq
    volumes:
      - /var/tz_workspace/photos:/workspace/photos
    command:
        python image_sender.py
  webapi:
    image: api
    profiles: ["web"]
    ports:
      - 80:5000
    depends_on:
      - rmq
    volumes:
      - /var/tz_workspace/photos:/workspace/photos
    command:
        flask run --host=0.0.0.0 --port=5000
  classifier:
    image: cls_effnet
    depends_on:
      - rmq
    volumes:
      - /var/tz_workspace/photos:/workspace/photos
      - ./configs:/workspace/configs
      - ./checkpoints:/workspace/checkpoints
    command:
      python classifier/run_cls.py
